# Generated by Django 3.2.8 on 2021-11-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0005_auto_20210723_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino retirable+', to='app_banco.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen retirable+', to='app_banco.cuenta'),
        ),
        migrations.CreateModel(
            name='Transaccion_Aportaciones_Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.CharField(choices=[('1', 'Deposito'), ('2', 'Retiro'), ('3', 'Transferencia')], max_length=1)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destino aportaciones historial+', to='app_banco.cuenta')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origen aportaciones historial+', to='app_banco.cuenta')),
            ],
            options={
                'verbose_name_plural': 'Transacciones de aportaciones historial',
            },
        ),
        migrations.CreateModel(
            name='Transaccion_Aportaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.CharField(choices=[('1', 'Deposito'), ('2', 'Retiro'), ('3', 'Transferencia')], max_length=1)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino aportaciones+', to='app_banco.cuenta')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen aportaciones+', to='app_banco.cuenta')),
            ],
            options={
                'verbose_name_plural': 'Transacciones de aportaciones',
            },
        ),
    ]
